apiVersion: v1
kind: Service
metadata:
  name: devbuddy-service
  labels:
    app: devbuddy
spec:
  # ClusterIP means this service is only accessible INSIDE the Kubernetes cluster.
  # The Ingress will talk to this Service, and this Service will load-balance to the Pods.
  type: ClusterIP
  
  # The Service finds the pods it needs to route traffic to using this selector
  selector:
    app: devbuddy
    
  ports:
  - port: 80           # The port the Service exposes internally
    targetPort: 80     # The port the Pod is listening on
    protocol: TCP
